import type { AppLocale } from './languages';

const en = {
  kicker: 'VRChat drawing automation', title: 'Drawing Studio', subtitle: 'Image vectorization, stroke planning, desktop input and OpenVR control',
  reset: 'Reset drawing settings', status_empty: 'No image', status_ready: 'Ready', status_running: 'Drawing', status_paused: 'Paused',
  preview: 'Stroke preview', preview_zoom: 'Preview zoom', open_image: 'Open image', image_files: 'Image files', empty_title: 'Choose an image', processing: 'Generating strokes...',
  strokes: 'Strokes', points: 'Points', progress: 'Progress', processing_section: 'Image processing', stroke_section: 'Stroke optimization', execution_section: 'Drawing control',
  mode: 'Processing mode', mode_lineart: 'Line art', mode_edges: 'Edge detection', mode_dither: 'Dither shading', mode_ai: 'AI line art', threshold: 'Threshold', blur: 'Blur', resolution: 'Resolution', prune: 'Noise pruning',
  invert: 'Invert', bridge_gaps: 'Connect gaps', optimize_path: 'Shortest pen travel', min_length: 'Minimum stroke', smoothing: 'Smoothing', simplify: 'Simplification', merge: 'Stroke merge',
  ai_model: 'Line model', ai_model_imageline: 'image-to-line (ONNX)', ai_model_anime2sketch: 'Anime2Sketch (no artifacts)', contrast: 'Contrast boost', artifact_removal: 'Artifact removal', model_size: 'Model size', lift_speed: 'Pen-lift speed',
  sensitivity: 'Sensitivity', vertical_stretch: 'Vertical scale', point_delay: 'Point delay', start_delay: 'Start delay', focus_vrchat: 'Focus VRChat', hotkeys: 'Global hotkeys',
  generate: 'Generate', regenerate: 'Regenerate', start: 'Start', stop: 'Stop', pause: 'Pause', resume: 'Resume', pause_resume: 'Pause / resume', error_unknown: 'Drawing operation failed',
  open_vr: 'Open in headset', reset_section: 'Reset section',
  stage_decode: 'Decoding image', stage_binarize: 'Binarizing', stage_skeletonize: 'Thinning lines', stage_extract: 'Extracting strokes', stage_optimize: 'Optimizing path', stage_ready: 'Ready',
};

const zhCN = {
  kicker: 'VRChat 自动绘画', title: '绘画工作台', subtitle: '图像矢量化、笔画规划、桌面输入与 OpenVR 控制',
  reset: '重置绘画设置', status_empty: '未载入图片', status_ready: '已就绪', status_running: '绘制中', status_paused: '已暂停',
  preview: '笔画预览', preview_zoom: '预览缩放', open_image: '打开图片', image_files: '图片文件', empty_title: '选择一张图片', processing: '正在生成笔画...',
  strokes: '笔画', points: '路径点', progress: '进度', processing_section: '图像处理', stroke_section: '笔画优化', execution_section: '绘制控制',
  mode: '处理模式', mode_lineart: '线稿提取', mode_edges: '边缘检测', mode_dither: '抖动阴影', mode_ai: 'AI 增强线稿', threshold: '阈值', blur: '模糊', resolution: '处理分辨率', prune: '噪点修剪',
  invert: '反相', bridge_gaps: '连接断点', optimize_path: '最短提笔路径', min_length: '最短笔画', smoothing: '平滑窗口', simplify: '路径简化', merge: '笔画合并',
  ai_model: '线稿模型', ai_model_imageline: 'image-to-line (ONNX)', ai_model_anime2sketch: 'Anime2Sketch (无伪影)', contrast: '对比度增强', artifact_removal: '伪影去除', model_size: '模型处理尺寸', lift_speed: '提笔速度',
  sensitivity: '绘画灵敏度', vertical_stretch: '纵向拉伸', point_delay: '点间延迟', start_delay: '开始延迟', focus_vrchat: '自动聚焦 VRChat', hotkeys: '全局快捷键',
  generate: '生成笔画', regenerate: '重新生成', start: '开始绘画', stop: '停止', pause: '暂停', resume: '继续', pause_resume: '暂停 / 继续', error_unknown: '绘画操作失败',
  open_vr: '在头显中打开', reset_section: '重置本区',
  stage_decode: '解析图像', stage_binarize: '二值化处理', stage_skeletonize: '线条细化', stage_extract: '提取笔画', stage_optimize: '优化路径', stage_ready: '已就绪',
};

const localeOverrides: Partial<Record<AppLocale, Partial<typeof en>>> = {
  'zh-CN': zhCN,
  'zh-TW': { ...zhCN, title: '繪畫工作台', subtitle: '圖像向量化、筆畫規劃、桌面輸入與 OpenVR 控制', open_image: '開啟圖片', empty_title: '選擇一張圖片', processing: '正在產生筆畫...', strokes: '筆畫', points: '路徑點', processing_section: '圖像處理', stroke_section: '筆畫最佳化', execution_section: '繪製控制', generate: '產生筆畫', regenerate: '重新產生', start: '開始繪畫', pause_resume: '暫停 / 繼續', mode_ai: 'AI 增強線稿', ai_model: '線稿模型', ai_model_anime2sketch: 'Anime2Sketch (無偽影)', contrast: '對比度增強', artifact_removal: '偽影去除', model_size: '模型處理尺寸', lift_speed: '提筆速度', open_vr: '在頭顯中開啟', reset_section: '重置本區', stage_decode: '解析影像', stage_binarize: '二值化處理', stage_skeletonize: '線條細化', stage_extract: '提取筆畫', stage_optimize: '最佳化路徑', stage_ready: '已就緒' },
  yue: { ...zhCN, title: '繪畫工作台', open_image: '開啟圖片', empty_title: '揀一張圖片', processing: '正在產生筆畫...', generate: '產生筆畫', regenerate: '重新產生', start: '開始繪畫', pause_resume: '暫停 / 繼續', mode_ai: 'AI 增強線稿', ai_model: '線稿模型', ai_model_anime2sketch: 'Anime2Sketch (無偽影)', contrast: '對比度增強', artifact_removal: '偽影去除', model_size: '模型處理尺寸', lift_speed: '提筆速度', open_vr: '喺頭顯開', reset_section: '重設呢區', stage_decode: '解析圖像', stage_binarize: '二值化處理', stage_skeletonize: '線條細化', stage_extract: '提取筆畫', stage_optimize: '優化路徑', stage_ready: '已就緒' },
  'ja-JP': { kicker: 'VRChat 自動描画', title: 'ドローイングスタジオ', subtitle: '画像ベクター化、ストローク計画、デスクトップ入力、OpenVR 操作', reset: '描画設定をリセット', status_empty: '画像なし', status_ready: '準備完了', status_running: '描画中', status_paused: '一時停止', preview: 'ストロークプレビュー', open_image: '画像を開く', empty_title: '画像を選択', processing: 'ストロークを生成中...', strokes: 'ストローク', points: 'ポイント', progress: '進行状況', processing_section: '画像処理', stroke_section: 'ストローク最適化', execution_section: '描画操作', mode: '処理モード', mode_lineart: '線画', mode_edges: 'エッジ検出', mode_dither: 'ディザリング', mode_ai: 'AI 線画', threshold: 'しきい値', blur: 'ぼかし', resolution: '解像度', prune: 'ノイズ除去', invert: '反転', bridge_gaps: '断線をつなぐ', optimize_path: '最短移動', min_length: '最小ストローク', smoothing: 'スムージング', simplify: '単純化', merge: 'ストローク結合', ai_model: '線画モデル', ai_model_imageline: 'image-to-line (ONNX)', ai_model_anime2sketch: 'Anime2Sketch (ノイズ除去)', contrast: 'コントラスト強調', artifact_removal: 'ノイズ除去', model_size: 'モデル解像度', lift_speed: 'ペン持ち上げ速度', sensitivity: '感度', vertical_stretch: '縦伸縮', point_delay: '点間遅延', start_delay: '開始遅延', focus_vrchat: 'VRChat にフォーカス', hotkeys: 'グローバルホットキー', generate: '生成', regenerate: '再生成', start: '開始', stop: '停止', pause: '一時停止', resume: '再開', pause_resume: '一時停止 / 再開', open_vr: 'ヘッドセットで開く', reset_section: 'セクションをリセット', stage_decode: '画像を解析中', stage_binarize: '二値化中', stage_skeletonize: '線を細線化中', stage_extract: 'ストローク抽出中', stage_optimize: '経路を最適化中', stage_ready: '準備完了' },
  ko: { kicker: 'VRChat 자동 그리기', title: '드로잉 스튜디오', subtitle: '이미지 벡터화, 선 계획, 데스크톱 입력 및 OpenVR 제어', reset: '그리기 설정 초기화', status_empty: '이미지 없음', status_ready: '준비됨', status_running: '그리는 중', status_paused: '일시 정지', preview: '선 미리보기', open_image: '이미지 열기', empty_title: '이미지 선택', processing: '선을 생성하는 중...', strokes: '선', points: '포인트', progress: '진행률', processing_section: '이미지 처리', stroke_section: '선 최적화', execution_section: '그리기 제어', mode: '처리 모드', mode_lineart: '선화', mode_edges: '엣지 검출', mode_dither: '디더링', mode_ai: 'AI 선화', threshold: '임계값', blur: '흐림', resolution: '해상도', prune: '노이즈 제거', invert: '반전', bridge_gaps: '끊긴 선 연결', optimize_path: '최단 이동', min_length: '최소 선', smoothing: '부드럽게', simplify: '단순화', merge: '선 병합', ai_model: '선 모델', ai_model_imageline: 'image-to-line (ONNX)', ai_model_anime2sketch: 'Anime2Sketch (노이즈 제거)', contrast: '대비 강조', artifact_removal: '노이즈 제거', model_size: '모델 해상도', lift_speed: '펜 들기 속도', sensitivity: '감도', vertical_stretch: '세로 늘이기', point_delay: '점 간 지연', start_delay: '시작 지연', focus_vrchat: 'VRChat 포커스', hotkeys: '전역 단축키', generate: '생성', regenerate: '다시 생성', start: '시작', stop: '중지', pause: '일시 정지', resume: '계속', pause_resume: '일시 정지 / 계속', open_vr: '헤드셋에서 열기', reset_section: '섹션 초기화', stage_decode: '이미지 분석 중', stage_binarize: '이진화 중', stage_skeletonize: '선 얇게 하기', stage_extract: '획 추출 중', stage_optimize: '경로 최적화 중', stage_ready: '준비됨' },
  es: { kicker: 'Dibujo automático de VRChat', title: 'Estudio de dibujo', subtitle: 'Vectorización, planificación de trazos, entrada de escritorio y control OpenVR', reset: 'Restablecer ajustes', status_empty: 'Sin imagen', status_ready: 'Listo', status_running: 'Dibujando', status_paused: 'En pausa', preview: 'Vista previa de trazos', open_image: 'Abrir imagen', empty_title: 'Selecciona una imagen', processing: 'Generando trazos...', strokes: 'Trazos', points: 'Puntos', progress: 'Progreso', processing_section: 'Procesamiento de imagen', stroke_section: 'Optimización de trazos', execution_section: 'Control de dibujo', mode: 'Modo de proceso', mode_lineart: 'Línea', mode_edges: 'Detección de bordes', mode_dither: 'Tramado', mode_ai: 'Línea IA', threshold: 'Umbral', blur: 'Desenfoque', resolution: 'Resolución', prune: 'Eliminar ruido', invert: 'Invertir', bridge_gaps: 'Conectar huecos', optimize_path: 'Recorrido más corto', min_length: 'Trazo mínimo', smoothing: 'Suavizado', simplify: 'Simplificación', merge: 'Unir trazos', ai_model: 'Modelo de línea', ai_model_imageline: 'image-to-line (ONNX)', ai_model_anime2sketch: 'Anime2Sketch (sin artefactos)', contrast: 'Refuerzo de contraste', artifact_removal: 'Eliminar artefactos', model_size: 'Tamaño del modelo', lift_speed: 'Velocidad de levantar', sensitivity: 'Sensibilidad', vertical_stretch: 'Escala vertical', point_delay: 'Retardo entre puntos', start_delay: 'Retardo inicial', focus_vrchat: 'Enfocar VRChat', hotkeys: 'Atajos globales', generate: 'Generar', regenerate: 'Regenerar', start: 'Iniciar', stop: 'Detener', pause: 'Pausar', resume: 'Continuar', pause_resume: 'Pausar / continuar', open_vr: 'Abrir en casco', reset_section: 'Restablecer sección', stage_decode: 'Descodificando imagen', stage_binarize: 'Binarizando', stage_skeletonize: 'Adelgazando líneas', stage_extract: 'Extrayendo trazos', stage_optimize: 'Optimizando ruta', stage_ready: 'Listo' },
  fr: { kicker: 'Dessin automatique VRChat', title: 'Studio de dessin', subtitle: 'Vectorisation, planification des traits, saisie bureau et contrôle OpenVR', reset: 'Réinitialiser les réglages', status_empty: 'Aucune image', status_ready: 'Prêt', status_running: 'Dessin en cours', status_paused: 'En pause', preview: 'Aperçu des traits', open_image: 'Ouvrir une image', empty_title: 'Choisir une image', processing: 'Génération des traits...', strokes: 'Traits', points: 'Points', progress: 'Progression', processing_section: 'Traitement de l’image', stroke_section: 'Optimisation des traits', execution_section: 'Contrôle du dessin', mode: 'Mode de traitement', mode_lineart: 'Ligne', mode_edges: 'Détection de bord', mode_dither: 'Tramage', mode_ai: 'Ligne IA', threshold: 'Seuil', blur: 'Flou', resolution: 'Résolution', prune: 'Suppression de bruit', invert: 'Inverser', bridge_gaps: 'Relier les trous', optimize_path: 'Trajet le plus court', min_length: 'Trait minimum', smoothing: 'Lissage', simplify: 'Simplification', merge: 'Fusion des traits', ai_model: 'Modèle de ligne', ai_model_imageline: 'image-to-line (ONNX)', ai_model_anime2sketch: 'Anime2Sketch (sans artefacts)', contrast: 'Renforcement du contraste', artifact_removal: 'Suppression d’artefacts', model_size: 'Taille du modèle', lift_speed: 'Vitesse de levée', sensitivity: 'Sensibilité', vertical_stretch: 'Échelle verticale', point_delay: 'Délai entre points', start_delay: 'Délai initial', focus_vrchat: 'Cibler VRChat', hotkeys: 'Raccourcis globaux', generate: 'Générer', regenerate: 'Régénérer', start: 'Démarrer', stop: 'Arrêter', pause: 'Pause', resume: 'Reprendre', pause_resume: 'Pause / reprendre', open_vr: 'Ouvrir dans le casque', reset_section: 'Réinitialiser la section', stage_decode: 'Décodage de l’image', stage_binarize: 'Binarisation', stage_skeletonize: 'Amincissement des lignes', stage_extract: 'Extraction des traits', stage_optimize: 'Optimisation du trajet', stage_ready: 'Prêt' },
  ru: { kicker: 'Автоматическое рисование VRChat', title: 'Студия рисования', subtitle: 'Векторизация, планирование штрихов, ввод с ПК и управление OpenVR', reset: 'Сбросить настройки', status_empty: 'Нет изображения', status_ready: 'Готово', status_running: 'Рисование', status_paused: 'Пауза', preview: 'Предпросмотр штрихов', open_image: 'Открыть изображение', empty_title: 'Выберите изображение', processing: 'Создание штрихов...', strokes: 'Штрихи', points: 'Точки', progress: 'Прогресс', processing_section: 'Обработка изображения', stroke_section: 'Оптимизация штрихов', execution_section: 'Управление рисованием', mode: 'Режим обработки', mode_lineart: 'Линия', mode_edges: 'Поиск краёв', mode_dither: 'Дизеринг', mode_ai: 'Линия ИИ', threshold: 'Порог', blur: 'Размытие', resolution: 'Разрешение', prune: 'Удаление шума', invert: 'Инверсия', bridge_gaps: 'Соединить разрывы', optimize_path: 'Кратчайший путь', min_length: 'Минимальный штрих', smoothing: 'Сглаживание', simplify: 'Упрощение', merge: 'Объединение штрихов', ai_model: 'Модель линий', ai_model_imageline: 'image-to-line (ONNX)', ai_model_anime2sketch: 'Anime2Sketch (без артефактов)', contrast: 'Усиление контраста', artifact_removal: 'Удаление артефактов', model_size: 'Размер модели', lift_speed: 'Скорость подъёма', sensitivity: 'Чувствительность', vertical_stretch: 'Вертикальный масштаб', point_delay: 'Задержка между точками', start_delay: 'Задержка старта', focus_vrchat: 'Фокус на VRChat', hotkeys: 'Глобальные горячие клавиши', generate: 'Создать', regenerate: 'Пересоздать', start: 'Начать', stop: 'Остановить', pause: 'Пауза', resume: 'Продолжить', pause_resume: 'Пауза / продолжить', open_vr: 'Открыть в шлеме', reset_section: 'Сбросить раздел', stage_decode: 'Декодирование изображения', stage_binarize: 'Бинаризация', stage_skeletonize: 'Утоньшение линий', stage_extract: 'Извлечение штрихов', stage_optimize: 'Оптимизация пути', stage_ready: 'Готово' },
  pt: { title: 'Estúdio de desenho', open_image: 'Abrir imagem', empty_title: 'Escolha uma imagen', processing: 'Gerando traços...', strokes: 'Traços', points: 'Pontos', progress: 'Progresso', generate: 'Gerar', regenerate: 'Gerar novamente', start: 'Iniciar', stop: 'Parar', pause: 'Pausar', resume: 'Continuar' },
  pl: { title: 'Studio rysowania', open_image: 'Otwórz obraz', empty_title: 'Wybierz obraz', processing: 'Tworzenie pociągnięć...', strokes: 'Pociągnięcia', points: 'Punkty', progress: 'Postęp', generate: 'Generuj', regenerate: 'Generuj ponownie', start: 'Start', stop: 'Stop', pause: 'Pauza', resume: 'Wznów' },
  cs: { title: 'Kreslicí studio', open_image: 'Otevřít obrázek', empty_title: 'Vyberte obrázek', processing: 'Generování tahů...', strokes: 'Tahy', points: 'Body', progress: 'Průběh', generate: 'Generovat', regenerate: 'Generovat znovu', start: 'Spustit', stop: 'Zastavit', pause: 'Pozastavit', resume: 'Pokračovat' },
  hu: { title: 'Rajzstúdió', open_image: 'Kép megnyitása', empty_title: 'Válasszon képet', processing: 'Vonalak létrehozása...', strokes: 'Vonalak', points: 'Pontok', progress: 'Folyamat', generate: 'Létrehozás', regenerate: 'Újragenerálás', start: 'Indítás', stop: 'Leállítás', pause: 'Szünet', resume: 'Folytatás' },
  th: { title: 'สตูดิโอวาดภาพ', open_image: 'เปิดรูปภาพ', empty_title: 'เลือกรูปภาพ', processing: 'กำลังสร้างเส้น...', strokes: 'เส้น', points: 'จุด', progress: 'ความคืบหน้า', generate: 'สร้าง', regenerate: 'สร้างใหม่', start: 'เริ่ม', stop: 'หยุด', pause: 'พัก', resume: 'ทำต่อ' },
  vi: { title: 'Xưởng vẽ', open_image: 'Mở hình ảnh', empty_title: 'Chọn một hình ảnh', processing: 'Đang tạo nét vẽ...', strokes: 'Nét vẽ', points: 'Điểm', progress: 'Tiến độ', generate: 'Tạo', regenerate: 'Tạo lại', start: 'Bắt đầu', stop: 'Dừng', pause: 'Tạm dừng', resume: 'Tiếp tục' },
};

export const drawingMessages = Object.fromEntries(
  (['cs', 'zh-CN', 'en-US', 'ja-JP', 'es', 'fr', 'hu', 'ko', 'pl', 'pt', 'ru', 'th', 'vi', 'yue', 'zh-TW'] as AppLocale[])
    .map(locale => [locale, { drawing: { ...en, ...(localeOverrides[locale] || {}) }, sidebar: { drawing: (localeOverrides[locale]?.title || en.title) } }]),
) as Record<AppLocale, { drawing: typeof en; sidebar: { drawing: string } }>;
